### ISSUE TITLE
Crash: TypeError: Cannot read property 'onClose' of undefined

### ISSUE THREAD

**Issue by euvs** [academia-de-codigo/react-semantic-toasts#1]
I get occasional crashes on this line:
https://github.com/academia-de-codigo/react-semantic-toasts/blob/1de7c5a5418161d5b7726cb651c487dc329e133a/lib/semantic-toast-container.jsx#L55

Steps to reproduce:
1. Click on the close 'x' button at the same time when timeout happens.

I seems `onClose` method is called twice and at the same time - from the mouse click and from the timeout method.

**Comment by ferrao** [comment]
Thanks for reporting @euvs, have just published a new version.
