### ISSUE TITLE
Hard to override css

### ISSUE THREAD

**Issue by watashiarc** [academia-de-codigo/react-semantic-toasts#11]
It looks like react-semantic-toasts does css imports directly into component jsx files. Since I use semantic-ui as a CSS framework base for most of my components, I have a lot of css that I override. When I imported react-semantic-toasts, I noticed a lot of my css was being override and finally found out that the react-semantic-toasts jsx files import css files directly. Is there a way we can separate the tight coupling of css imports?

**Comment by ferrao** [comment]
Should be easy to override css now @watashiarc, the library does not depend on `semantic-ui-css` anymore.
