### ISSUE TITLE
It appears icon is required?

### ISSUE THREAD

**Issue by csterritt** [academia-de-codigo/react-semantic-toasts#12]
Hello --

First, thanks for doing this library! It works very well, and looks nice.

However, I just started getting an error (...I believe...) where it complains that the icon is required.

My example code is:

    toast({
            title: 'Success!',
            description: 'Saved successfully.',
            time: 3000,
            type: 'success'
          }
        )

The error message is:

    Warning: Failed prop type: The prop `icon` is marked as required in `SemanticToast`, but its value is `undefined`.

The documentation says that the `icon` argument is optional.  I fixed my code with:

    toast({
            title: 'Success!',
            description: 'Saved successfully.',
            time: 3000,
            type: 'success',
            icon: 'announcement'
          }
        )

but it seems unfortunate that I have to look in the code to find the right icon to use.

Thanks!

**Comment by ferrao** [comment]
Thanks for reporting @csterritt, not sure how that one slipped under the radar..
