### ISSUE TITLE
Can you make semantic-ui-css optional?

### ISSUE THREAD

**Issue by vfonic** [academia-de-codigo/react-semantic-toasts#13]
Oi Rui!

Thanks for the great package! I've set it up and it's really easy to use and nice looking with those tiny animations. :)

I don't use semantic-ui-css in my project and it's not a required dependency of semantic-ui-react. However, this package fails if semantic-ui-css is not added. Please note that semantic-ui-css is a package that weights about 600KB. I've checked similar issues and noticed you moved the dependency to peer dependencies. This still doesn't solve the issue.

Would it be possible to have unstyled version of the package or some similar solution?

Thanks!

**Comment by ferrao** [comment]
Hi @vfonic, I am glad you enjoy the package!

It is probably easy to import only the specific css components that the package needs, but if you don't mind, before moving forward on something like that, I would like to better understand the motivations for it. 

For me, Semantic UI is mainly a CSS framework and it never occurred to me that somebody would like to use it without the css at all, or that is was even possible for such a thing, so I am very curious about your use case.

Furthermore, I see it as a concern of the build system tools (webpack, postcss, etc.) to drop any unused CSS and just keeping on the bundle the stuff you actually use.

**Comment by ferrao** [comment]
I had a better look at this. 

The `semantic-ui-css` package comes in at aprox 820k (123k gzipped), but care has already been taken for the package to import only the css components it requires:

```
// on SemanticToastContainer component
import 'semantic-ui-css/components/reset.min.css';
import 'semantic-ui-css/components/site.min.css';
import 'semantic-ui-css/components/container.min.css';
import 'semantic-ui-css/components/icon.min.css';

// on SemanticToast component
import 'semantic-ui-css/components/message.min.css';
import 'semantic-ui-css/components/header.min.css';

// on withTransition HOC
import 'semantic-ui-css/components/transition.min.css';
```

I understand that all of these combined will probably weight in about 600k unzipped, but again, the assumption is that if you are using Semantic UI you are probably importing most of this CSS already anyway and a proper build process setup will drop all unused styles. Please let me know what I am missing here ;)

**Comment by vfonic** [comment]
Thanks for investing the time to look into this.

I had some issues where, if I imported css styles for Semantic UI, it would override my CSS-in-JS styles. I found it easier to just include the css file directly from the CDN, since it had lower importance in CSS (<link href> vs <style> tag)

Another use case where you could use react semantic UI, but not the css package is when you want to customize the semantic ui theme: https://react.semantic-ui.com/theming
Seems like the most recommended way is to build the css yourself by using less, instead of including the css package.

**Comment by ferrao** [comment]
Hi @vfonic , just pushed a new version to npm without any css dependencies :)
