### ISSUE TITLE
Any chance of upgrading the semantic-ui-react peerDependencie to 0.83.x?

### ISSUE THREAD

**Issue by diegosiao** [academia-de-codigo/react-semantic-toasts#14]
I could not install this component because I am using the most recent semantic-ui-react, is there any plan to support it?
Thanks in advance!

**Comment by ferrao** [comment]
Just pushed a new version to npm with support for `0.83.x` and `0.84.x`.

**Comment by diegosiao** [comment]
Great man!

Thanks
