### ISSUE TITLE
CSS Still included (0.4.0)

### ISSUE THREAD

**Issue by adam-26** [academia-de-codigo/react-semantic-toasts#15]
Hi @ferrao,

It appears the new version you released to NPM still includes all `.css` files in the `/build` directory. Did you forget to re-build before publishing to NPM?

Also, can you remove the  `import '../styles/react-semantic-alert.css';` statement from the `semantic-toast-container.jsx` file, and instead add to the documentation that developers need to **import** that file?? The reason for this, is that build tools (webpack, babel, etc..) by default do not include code that is in the `node_modules` directory. It would be better if the `.css` file you provided is **imported** so that it can easily be included in the local build packaging.

Thanks for the good work.

**Comment by ferrao** [comment]
Hi @adam-26, you are totally right, I did forgot to re-build before publishing and also on the imported css. Both changes fixed and published, thanks for the feedback!
