### ISSUE TITLE
Custom transition?

### ISSUE THREAD

**Issue by ngocketit** [academia-de-codigo/react-semantic-toasts#19]
Hi,

Thanks for the great work! Is it possible to change or turn off the transition? The animation looks cool but I guess something simpler (such as sliding up/down) would be more preferred.

**Comment by ferrao** [comment]
You can change it to any supported [SemanticUI animation](https://semantic-ui.com/modules/transition.html) via the `animation` prop of the `SemanticToastContainer`.
