### ISSUE TITLE
Build error due to require("... .css") codes

### ISSUE THREAD

**Issue by dehypnosis** [academia-de-codigo/react-semantic-toasts#2]
Can you make a css detached version?
Or Please let me know how to prevent build confliction...

```sh
/Users/dehypnosis/dev/syncodax-dev/web/node_modules/semantic-ui-css/components/reset.min.css:9
 */*,:after,:before{-webkit-box-sizing:inherit;box-sizing:inherit}html{-webkit-box-sizing:border-box;box-sizing:border-box}input[type=email],input[type=password],input[type=search],input[type=text]{-webkit-appearance:none;-moz-appearance:none}/*! normalize.css v7.0.0 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,footer,header,nav,section{display:block}h1{font-size:2em;margin:.67em 0}figcaption,figure,main{display:block}figure{margin:1em 40px}hr{-webkit-box-sizing:content-box;box-sizing:content-box;height:0;overflow:visible}pre{font-family:monospace,monospace;font-size:1em}a{background-color:transparent;-webkit-text-decoration-skip:objects}abbr[title]{border-bottom:none;text-decoration:underline;-webkit-text-decoration:underline dotted;text-decoration:underline dotted}b,strong{font-weight:inherit}b,strong{

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dehypnosis/dev/syncodax-dev/web/node_modules/react-semantic-toasts/build/semantic-toast-container.js:4:1)
```

**Comment by ferrao** [comment]
Hi @dehypnosis, not sure I understand the problem, can you provide some additional info on how to reproduce this issue?

**Comment by adam-bernau** [comment]
Hi, I got same error with default nextjs configuraton.

**Comment by ferrao** [comment]
@dehypnosis, @adam-bernau, I have no ideia on how to replicate this issue, can you please let me provide some information on how to trigger it?

**Comment by dehypnosis** [comment]
Can replicate this error when build a fresh react project with webpack

**Comment by ferrao** [comment]
@dehypnosis, I have it working on several react projects with webpack without any problems, so I still do not understands the issue you are experiencing.

I have created a code sandbox [here](https://github.com/CompuIves/codesandbox-client/issues/910) to prove that it works.

For some reason [the icons are not showing up when the code is executed](https://github.com/CompuIves/codesandbox-client/issues/910), but if you download the project and install locally it runs just fine.

**Comment by ferrao** [comment]
This package no longer depends directly on `semantic-ui-css` or `semantic-ui-react` as they have been moved to peer dependencies, so that might be what was causing your issues.

**Comment by ferrao** [comment]
A css detached version has been published to npm, I hope it works better for you @dehypnosis.
