### ISSUE TITLE
Ability to set description to be a JSX component

### ISSUE THREAD

**Issue by peterbe** [academia-de-codigo/react-semantic-toasts#20]
I would expect to be able to do:

```jsx
toast({
  type: 'warning',
  icon: 'envelope',
  title: 'Warning Toast',
  description: <p>THis is a <b>node</b></p>,
  time: 5000,
});
```

If you try you get this error:
```
Warning: Failed prop type: Invalid prop `description` of type `object` supplied to `SemanticToast`, expected `string`.
```

This is what Ant does: https://ant.design/components/message/#API
The `content` argument's type is `string|ReactNode`.

**Comment by peterbe** [comment]
Well, using a `<p>` might not be a great idea since it's a block, but whatever. Is it perhaps a limitation of Semantic-UI?

**Comment by peterbe** [comment]
yay! Looking forward to the next release to test.

**Comment by ferrao** [comment]
It's published to npm already @peterbe
