### ISSUE TITLE
Works with semantic-ui-react 0.85

### ISSUE THREAD

**Issue by peterbe** [academia-de-codigo/react-semantic-toasts#21]
I get this warning:
```
warning " > react-semantic-toasts@0.5.0" has incorrect peer dependency "semantic-ui-react@0.82.x || 0.83.x || 0.84.x".
```

...because [this lib specifically doesn't support 0.85](https://github.com/academia-de-codigo/react-semantic-toasts/blob/ff03b7f97f429a94fe7a5c17da98a46a12f37a65/package.json#L50). But I'm able to run it just fine with ` "semantic-ui-react": "0.85.0",` in my project.

**Comment by ferrao** [comment]
Thanks for reporting @peterbe , I have updated the dependencies already.
