### ISSUE TITLE
Toast show behind semantic-ui modal box

### ISSUE THREAD

**Issue by kaung8khant** [academia-de-codigo/react-semantic-toasts#29]
I tried changing z-index of toast but not working. Is there any workaround for this?

**Comment by kaung8khant** [comment]
Use `SemanticToastContainer` in modal to position toast message

**Comment by Kbre** [comment]
I found a way for this to work. Just in case someone ended here looking for a solution to this problem: please take a look at [this](https://stackoverflow.com/a/74547452/18439112)
