### ISSUE TITLE
Render override other component

### ISSUE THREAD

**Issue by Jeromearsene** [academia-de-codigo/react-semantic-toasts#30]
I discover that result HTML override other HTML.

In my example, i have a Semantic dropdown in top right.
My `ToastContainer` is in top right (by default). The HTML render is a div with classes `ui-alerts top-right `. With this div, my dropdown is not clickable !
I think it will be better to put this div in `display none` while is not active.

My actual approach is too change padding to 0px for force to have no width when toast container is empty.

Thanks

**Comment by ferrao** [comment]
Thanks for reporting, fixed in https://github.com/academia-de-codigo/react-semantic-toasts/commit/3343b1e287625d744f8c63cc53088c7ba8e96b4c, just published a new version.
