### ISSUE TITLE
Types missing ToastSize and ToastColor interfaces

### ISSUE THREAD

**Issue by carsonfarmer** [academia-de-codigo/react-semantic-toasts#34]
Getting `Cannot find name 'ToastSize'.` and `Cannot find name 'ToastColor'.` on `tsc` in parent project. I think these just need to use `SemanticCOLORS` and `SemanticSIZES`.

**Comment by PawelJ-PL** [comment]
Hi,

I can see that fix has been merged to the master 3 days ago, but it's not released yet. Could You please release it? 
Currently it's impossible to use library with typescript (none of 0.6.x version is working), but the library looks like what I was looking for.

**Comment by ferrao** [comment]
Just published a new version @PawelJ-PL
