### ISSUE TITLE
Compilation fails with "Statements are not allowed in ambient contexts.  TS1036"

### ISSUE THREAD

**Issue by PawelJ-PL** [academia-de-codigo/react-semantic-toasts#36]
Hi

I'm trying to use library in my project, but TS compiler fails with following error:

```
TypeScript error in node_modules/react-semantic-toasts/build/index.d.ts(35,2):
Statements are not allowed in ambient contexts.  TS1036

    33 | 
    34 |     export { SemanticToastContainer, toast, ToastOptions }
  > 35 | };
       |  ^
    36 | 
```

I'm using `TypeScript 3.5.3` and `react-semantic-toasts  0.6.2`

**Comment by PawelJ-PL** [comment]
Prepared PR, which fixes problem: https://github.com/academia-de-codigo/react-semantic-toasts/pull/37

**Comment by ferrao** [comment]
@PawelJ-PL please try 0.6.3

**Comment by PawelJ-PL** [comment]
I've checked version 0.6.3 and everything looks fine. Finally I was able to compile project.
