### ISSUE TITLE
Duplicate import of Semantic UI

### ISSUE THREAD

**Issue by sivadass** [academia-de-codigo/react-semantic-toasts#4]
Hi Guys, 

First of all,  thank you for this great plugin.

I have found one issue, `react-semantic-toasts` package imports a duplicate version of Semantic UI package, this in return increases my bundle size.

Please check the screenshot below:

![duplicate-import-of-react-toast](https://user-images.githubusercontent.com/10391786/45096216-a8540480-b13d-11e8-9116-0bde67f89899.png)

How can I resolve this?

**Comment by ferrao** [comment]
Thanks for reporting @sivadass, I will have a look as soon as I can.

**Comment by ferrao** [comment]
Had a look at this and it is caused by different versions of `semantic-ui-react` dependencies between your project and `react-semantic-toasts`.

I have just released a new version of the package with dependency updates, which together with `npm dedupe` should eliminate this issue.

**Comment by sivadass** [comment]
Thanks a lot @ferrao 
Have a good day! :)

**Comment by ferrao** [comment]
Actually @sivadass the way to go and preventing this issue from occurring again is to use peer dependencies. I have just published a new `0.3.6` version to npm, which does not depend directly on react or semantic ui anymore and should not give you any more trouble.
