### ISSUE TITLE
./node_modules/react-semantic-toasts/build/semantic-toast-container.js Module not found: Can't resolve 'semantic-ui-css/components/container.min.css'

### ISSUE THREAD

**Issue by Togrias** [academia-de-codigo/react-semantic-toasts#5]
I'm getting the above error when I compile. Am using the default Semantic UI gulp build tool rather than the css version. Is it incompatible?

**Comment by ferrao** [comment]
I have moved `semantic-ui-react` and `semantic-ui-css` to peer dependencies, so you have to install those explicitly.

I have now updated the install instructions and pushed a new version to make it clear.
