### ISSUE TITLE
semantic-ui-react 2.0.3?

### ISSUE THREAD

**Issue by yurikhan** [academia-de-codigo/react-semantic-toasts#55]
Hello, is this library being maintained? The current version of semantic-ui-react is 2.0.3 but react-semantic-toasts declares a peer dependency compatible with up to 0.88.

**Comment by ferrao** [comment]
Hi @yurikhan  we do not use it internally anymore and that is why its dependencies are outdated, but feel free to submit a PR and I will merge.

**Comment by Zerquix18** [comment]
Hello @ferrao are you still open to this? I'm looking forward to updating my semantic-ui-react version but it doesn't allow me because of the peer dependencies of this one.

**Comment by Zerquix18** [comment]
Also, it seems to lock me on React 16.x.x. Any chance it may work on React 17? Or should I test?

**Comment by ferrao** [comment]
Hi @Zerquix18, totally opened to merge a PR, please go ahead!

**Comment by Zerquix18** [comment]
Just had a look at it and it looks like `semantic-ui-react` is used?:

https://github.com/academia-de-codigo/react-semantic-toasts/blob/master/lib/semantic-toast.jsx#L3
https://github.com/academia-de-codigo/react-semantic-toasts/blob/master/lib/with-transition.jsx#L2

The use seems very simple. I guess it would be fine to allow any version?

I tried running `npm run build` using React "16.x.x || 17.x.x" and semantic ui react "*" as peer dependencies and it seemed to work.

**Comment by ferrao** [comment]
> I tried running `npm run build` using React "16.x.x || 17.x.x" and semantic ui react "*" as peer dependencies and it seemed to work.

Just open a PR with the updated dependencies and I will merge it @Zerquix18
