### ISSUE TITLE
Running npm install does not pull latest code from master

### ISSUE THREAD

**Issue by akashduggal567** [academia-de-codigo/react-semantic-toasts#64]
@ferrao  Still facing the same issue raised in #55 even after the merge of #61 
if i run `npm i react-semantic-toasts` on local.

Below is the screenshot of peer dependencies in local for the version `0.6.5`
<img width="734" alt="Screen Shot 2022-02-19 at 8 18 53 PM" src="https://user-images.githubusercontent.com/39848504/154805888-1a224520-422f-4694-a81e-f2bb1d0665b0.png">

**Comment by ferrao** [comment]
It has not yet been pushed to `npm` due to [this](https://github.com/academia-de-codigo/react-semantic-toasts/pull/61#issuecomment-976364872). If you/someone fixes it, I will push it. @Zerquix18 , @baskin ?

**Comment by ferrao** [comment]
Have just published v0.6.6 to npm @akashduggal567
